// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiEyQ2RCSKwH0TYfJc6PLXnLY9h9VBFSQ',
    appId: '1:1067422879074:web:44514dc8a13a9dc3d9303b',
    messagingSenderId: '1067422879074',
    projectId: 'spendwise-47c25',
    authDomain: 'spendwise-47c25.firebaseapp.com',
    storageBucket: 'spendwise-47c25.appspot.com',
    measurementId: 'G-10NW12RWY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6oJXMEaWFYlBR2eSMy7mI5THNJq6IrXM',
    appId: '1:1067422879074:android:a0c7a6e2424a7ca7d9303b',
    messagingSenderId: '1067422879074',
    projectId: 'spendwise-47c25',
    storageBucket: 'spendwise-47c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt36wsH-Wq-gNoZomAkCVb6PFCWomMcqo',
    appId: '1:1067422879074:ios:33f59dcda8d9af6bd9303b',
    messagingSenderId: '1067422879074',
    projectId: 'spendwise-47c25',
    storageBucket: 'spendwise-47c25.appspot.com',
    iosBundleId: 'com.example.financialManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt36wsH-Wq-gNoZomAkCVb6PFCWomMcqo',
    appId: '1:1067422879074:ios:46eee88f4932ce68d9303b',
    messagingSenderId: '1067422879074',
    projectId: 'spendwise-47c25',
    storageBucket: 'spendwise-47c25.appspot.com',
    iosBundleId: 'com.example.financialManagementApp.RunnerTests',
  );
}
